In [1]:
import pandas as pd
from sklearn.neighbors import DistanceMetric
from scipy.spatial.distance import pdist, squareform
from math import radians
import numpy as np

In [2]:
locations = pd.read_csv('coffee_clean.csv') 
locations2 = pd.read_csv('coffee_clean.csv') 
locations

      latitude  longitude       Store
0    39.075001 -94.379703     Dunkin'
1    38.405691 -90.376802  McDonald's
2    38.445494 -90.374454  McDonald's
3    38.437043 -90.377478  McDonald's
4    38.418379 -90.390784  McDonald's
..         ...        ...         ...
313  38.629806 -90.216753   Starbucks
314  38.630655 -90.191852   Starbucks
315  38.624702 -90.193569   Starbucks
316  38.625172 -90.190579   Starbucks
317  38.626002 -90.188291   Starbucks

[318 rows x 3 columns]

In [3]:
x = np.arange(len(locations))
locations['num'] = x
locations['num'] = locations['num'].astype(str)
locations['Stores'] = locations['Store']+locations['num']
locations = locations[['Stores', 'latitude', 'longitude']].rename(columns={'Stores':'Store'})
locations1 = locations[['Store', 'latitude', 'longitude']]
locations1

            Store   latitude  longitude
0        Dunkin'0  39.075001 -94.379703
1     McDonald's1  38.405691 -90.376802
2     McDonald's2  38.445494 -90.374454
3     McDonald's3  38.437043 -90.377478
4     McDonald's4  38.418379 -90.390784
..            ...        ...        ...
313  Starbucks313  38.629806 -90.216753
314  Starbucks314  38.630655 -90.191852
315  Starbucks315  38.624702 -90.193569
316  Starbucks316  38.625172 -90.190579
317  Starbucks317  38.626002 -90.188291

[318 rows x 3 columns]

In [4]:
locations['latitude'] = np.radians(locations['latitude'])
locations['longitude'] = np.radians(locations['longitude'])
locations

            Store  latitude  longitude
0        Dunkin'0  0.681987  -1.647237
1     McDonald's1  0.670306  -1.577373
2     McDonald's2  0.671000  -1.577332
3     McDonald's3  0.670853  -1.577385
4     McDonald's4  0.670527  -1.577617
..            ...       ...        ...
313  Starbucks313  0.674217  -1.574579
314  Starbucks314  0.674232  -1.574145
315  Starbucks315  0.674128  -1.574175
316  Starbucks316  0.674136  -1.574123
317  Starbucks317  0.674151  -1.574083

[318 rows x 3 columns]

In [5]:
dist = DistanceMetric.get_metric('haversine')
locations[['latitude','longitude']].to_numpy()

array([[ 0.68198742, -1.64723656],
       [ 0.67030576, -1.57737276],
       [ 0.67100046, -1.57733178],
       [ 0.67085296, -1.57738456],
       [ 0.67052721, -1.57761679],
       [ 0.6813063 , -1.64534012],
       [ 0.68116812, -1.64534489],
       [ 0.68077784, -1.64502401],
       [ 0.68125674, -1.64594996],
       [ 0.6808332 , -1.64543933],
       [ 0.63956566, -1.62704358],
       [ 0.63950916, -1.62776169],
       [ 0.63990069, -1.62734655],
       [ 0.64032087, -1.62696416],
       [ 0.65123556, -1.5628508 ],
       [ 0.65105499, -1.56352748],
       [ 0.65121785, -1.5628725 ],
       [ 0.65098917, -1.56336894],
       [ 0.6482177 , -1.64618551],
       [ 0.64889118, -1.64627574],
       [ 0.69452852, -1.63277429],
       [ 0.69455771, -1.63343403],
       [ 0.67989129, -1.61087935],
       [ 0.67972178, -1.61141855],
       [ 0.67909983, -1.61150971],
       [ 0.68003707, -1.61076299],
       [ 0.68055179, -1.61136385],
       [ 0.67996648, -1.61236925],
       [ 0.68658987, -1.64495566],
       [ 0.6864834 , -1.64540273],
       [ 0.65923022, -1.57859482],
       [ 0.65952686, -1.57817649],
       [ 0.65959527, -1.57830883],
       [ 0.6668793 , -1.57780981],
       [ 0.66697789, -1.57755941],
       [ 0.6669377 , -1.57761994],
       [ 0.67894047, -1.6499002 ],
       [ 0.67892162, -1.64991212],
       [ 0.6817845 , -1.63608613],
       [ 0.68074057, -1.63598612],
       [ 0.68207386, -1.64840285],
       [ 0.68246762, -1.64823315],
       [ 0.68199103, -1.64782938],
       [ 0.68204909, -1.64761502],
       [ 0.68147669, -1.64830769],
       [ 0.68193472, -1.64723637],
       [ 0.68143221, -1.6478638 ],
       [ 0.68123888, -1.64683193],
       [ 0.6815903 , -1.64711104],
       [ 0.68150696, -1.64699135],
       [ 0.68272529, -1.64728816],
       [ 0.67281631, -1.60831506],
       [ 0.67320203, -1.60875661],
       [ 0.67333561, -1.60907883],
       [ 0.67288004, -1.60918547],
       [ 0.67335814, -1.60980742],
       [ 0.67333257, -1.60910894],
       [ 0.67334954, -1.60953028],
       [ 0.67283723, -1.60928496],
       [ 0.64725493, -1.6498717 ],
       [ 0.64777819, -1.64950272],
       [ 0.64735459, -1.6489346 ],
       [ 0.64715302, -1.64894056],
       [ 0.64784806, -1.648917  ],
       [ 0.64682177, -1.64958382],
       [ 0.64704702, -1.64893718],
       [ 0.64670449, -1.64959468],
       [ 0.64674744, -1.64990783],
       [ 0.64698842, -1.64922463],
       [ 0.68243358, -1.65079456],
       [ 0.68214821, -1.65064959],
       [ 0.68184758, -1.65082198],
       [ 0.6817189 , -1.65091486],
       [ 0.68140546, -1.65098225],
       [ 0.68043488, -1.65121663],
       [ 0.67967165, -1.65120893],
       [ 0.68026542, -1.65100049],
       [ 0.68360094, -1.65068821],
       [ 0.68324175, -1.65031993],
       [ 0.68370095, -1.6499516 ],
       [ 0.68466753, -1.65066659],
       [ 0.68431634, -1.65017964],
       [ 0.68416835, -1.64933667],
       [ 0.68465179, -1.65012247],
       [ 0.68294302, -1.64939831],
       [ 0.6825115 , -1.6496799 ],
       [ 0.68234514, -1.65022965],
       [ 0.68188663, -1.64968734],
       [ 0.68122463, -1.64939859],
       [ 0.68087154, -1.65064792],
       [ 0.67930815, -1.65080323],
       [ 0.68025951, -1.65030405],
       [ 0.68063018, -1.64896704],
       [ 0.67923509, -1.64998321],
       [ 0.67986979, -1.6497864 ],
       [ 0.68009634, -1.64931309],
       [ 0.68007939, -1.64808678],
       [ 0.67869292, -1.65121052],
       [ 0.68434283, -1.65181837],
       [ 0.68496616, -1.65212425],
       [ 0.68531074, -1.65066952],
       [ 0.68499136, -1.65077988],
       [ 0.68535486, -1.6484836 ],
       [ 0.68493752, -1.64868144],
       [ 0.68492143, -1.64863164],
       [ 0.70188514, -1.61586478],
       [ 0.70133592, -1.61568761],
       [ 0.67664193, -1.5844543 ],
       [ 0.67924342, -1.64692583],
       [ 0.67899598, -1.6465245 ],
       [ 0.67937543, -1.64757495],
       [ 0.67930416, -1.64688766],
       [ 0.68832227, -1.61348678],
       [ 0.68825747, -1.6132616 ],
       [ 0.64300916, -1.64749081],
       [ 0.64337894, -1.64727784],
       [ 0.66038608, -1.64685823],
       [ 0.67550365, -1.58244678],
       [ 0.67728004, -1.58423198],
       [ 0.67757216, -1.5830162 ],
       [ 0.67721788, -1.5830023 ],
       [ 0.67647009, -1.58303006],
       [ 0.66551152, -1.61743053],
       [ 0.6647705 , -1.61775869],
       [ 0.67206477, -1.58264022],
       [ 0.67167562, -1.58404521],
       [ 0.65819164, -1.56890526],
       [ 0.65818759, -1.56889069],
       [ 0.64205729, -1.57831522],
       [ 0.64151368, -1.57792155],
       [ 0.68114124, -1.64833202],
       [ 0.66215516, -1.60181921],
       [ 0.66225518, -1.60196072],
       [ 0.67559189, -1.62778014],
       [ 0.67496384, -1.62754735],
       [ 0.67560203, -1.62782241],
       [ 0.64386822, -1.56269962],
       [ 0.64376503, -1.56311297],
       [ 0.64340247, -1.56350438],
       [ 0.64946683, -1.62925854],
       [ 0.64942415, -1.6271488 ],
       [ 0.6493345 , -1.62771843],
       [ 0.64940848, -1.62796598],
       [ 0.65009614, -1.62859151],
       [ 0.64996955, -1.62846118],
       [ 0.64990257, -1.62770375],
       [ 0.64826173, -1.62762535],
       [ 0.64821719, -1.6279989 ],
       [ 0.64892466, -1.6274545 ],
       [ 0.64856439, -1.6278122 ],
       [ 0.6485233 , -1.62712838],
       [ 0.6482876 , -1.62766666],
       [ 0.64903817, -1.62767317],
       [ 0.64819221, -1.62949608],
       [ 0.64856997, -1.62864652],
       [ 0.64821291, -1.62833899],
       [ 0.64896144, -1.62833603],
       [ 0.6489138 , -1.62833879],
       [ 0.67670938, -1.57937268],
       [ 0.67752575, -1.57976669],
       [ 0.6769821 , -1.57976119],
       [ 0.67682265, -1.58004762],
       [ 0.67625421, -1.58089316],
       [ 0.67613291, -1.58187   ],
       [ 0.6695201 , -1.58785778],
       [ 0.69349253, -1.65458067],
       [ 0.69332899, -1.65439501],
       [ 0.69314095, -1.65580938],
       [ 0.6931269 , -1.65584125],
       [ 0.69467513, -1.65485238],
       [ 0.69427727, -1.65461721],
       [ 0.69414061, -1.65462418],
       [ 0.69383935, -1.65403361],
       [ 0.67433459, -1.57420246],
       [ 0.67418877, -1.57413928],
       [ 0.67391702, -1.57466967],
       [ 0.67437912, -1.57505017],
       [ 0.67345751, -1.57560865],
       [ 0.67357555, -1.57592206],
       [ 0.67326506, -1.574869  ],
       [ 0.67502934, -1.57517035],
       [ 0.67308215, -1.57592126],
       [ 0.67350775, -1.57506359],
       [ 0.67412479, -1.5758139 ],
       [ 0.67671746, -1.58095193],
       [ 0.67697166, -1.5823443 ],
       [ 0.67704327, -1.58062855],
       [ 0.67715555, -1.58159431],
       [ 0.6770894 , -1.58167343],
       [ 0.67703003, -1.58136883],
       [ 0.67649212, -1.58219586],
       [ 0.67668566, -1.63599059],
       [ 0.67682621, -1.63602328],
       [ 0.64124395, -1.60344631],
       [ 0.64079218, -1.60351315],
       [ 0.6455245 , -1.60528574],
       [ 0.64568465, -1.60511234],
       [ 0.6798106 , -1.61141707],
       [ 0.679097  , -1.61157366],
       [ 0.67977489, -1.61085608],
       [ 0.67862733, -1.61264625],
       [ 0.68004603, -1.61222798],
       [ 0.67337993, -1.60934866],
       [ 0.67338264, -1.60936753],
       [ 0.68210449, -1.65075785],
       [ 0.68158619, -1.65093823],
       [ 0.68141235, -1.65097827],
       [ 0.68091545, -1.65091507],
       [ 0.67967125, -1.65119153],
       [ 0.68406658, -1.65071307],
       [ 0.68498311, -1.65194949],
       [ 0.68497894, -1.64863464],
       [ 0.67559645, -1.62780536],
       [ 0.67559572, -1.62780375],
       [ 0.64934649, -1.62797146],
       [ 0.65002366, -1.62860381],
       [ 0.64896145, -1.62767708],
       [ 0.64865548, -1.62875189],
       [ 0.64856376, -1.62860338],
       [ 0.64895824, -1.62902884],
       [ 0.6482903 , -1.62834104],
       [ 0.64821534, -1.62831032],
       [ 0.64864839, -1.6287981 ],
       [ 0.6769082 , -1.58014604],
       [ 0.67618243, -1.58187788],
       [ 0.67415678, -1.57412652],
       [ 0.67381248, -1.57433278],
       [ 0.67438116, -1.57535462],
       [ 0.67448345, -1.57535146],
       [ 0.67354443, -1.57612309],
       [ 0.67293686, -1.57537869],
       [ 0.67373263, -1.57501933],
       [ 0.6770768 , -1.5816695 ],
       [ 0.64668685, -1.64896858],
       [ 0.64725907, -1.64887983],
       [ 0.64730821, -1.64893535],
       [ 0.67446719, -1.58182545],
       [ 0.67338586, -1.58175752],
       [ 0.67489951, -1.58124574],
       [ 0.67577691, -1.58305068],
       [ 0.67487512, -1.58101139],
       [ 0.67443425, -1.58067927],
       [ 0.67360462, -1.58034621],
       [ 0.6761855 , -1.581878  ],
       [ 0.67356912, -1.58027371],
       [ 0.67407927, -1.57985731],
       [ 0.67405183, -1.57983399],
       [ 0.67659373, -1.58412157],
       [ 0.6767927 , -1.58301217],
       [ 0.67443239, -1.57961827],
       [ 0.67685453, -1.58299581],
       [ 0.67663471, -1.58448508],
       [ 0.67358009, -1.57947754],
       [ 0.67508404, -1.57951887],
       [ 0.67416256, -1.57920525],
       [ 0.67698945, -1.58172809],
       [ 0.67258946, -1.57946248],
       [ 0.67315014, -1.57908743],
       [ 0.67370956, -1.57838573],
       [ 0.67494267, -1.57840315],
       [ 0.67493388, -1.57838996],
       [ 0.67546777, -1.5785798 ],
       [ 0.67673056, -1.57935839],
       [ 0.67693048, -1.57947273],
       [ 0.67542368, -1.57813762],
       [ 0.6742646 , -1.57785995],
       [ 0.67330323, -1.5778972 ],
       [ 0.67200139, -1.5786105 ],
       [ 0.67209056, -1.5785244 ],
       [ 0.67291854, -1.5779641 ],
       [ 0.67750865, -1.58612616],
       [ 0.67309087, -1.57784742],
       [ 0.67752805, -1.5861677 ],
       [ 0.67642327, -1.57831971],
       [ 0.67255829, -1.58792981],
       [ 0.6763769 , -1.57823253],
       [ 0.67608005, -1.57773668],
       [ 0.67294682, -1.57744893],
       [ 0.67384781, -1.57720943],
       [ 0.67403962, -1.57687136],
       [ 0.67418476, -1.57677788],
       [ 0.67420658, -1.57673472],
       [ 0.67209469, -1.57734791],
       [ 0.67457543, -1.57669378],
       [ 0.67621191, -1.57721279],
       [ 0.67353601, -1.57671924],
       [ 0.67617973, -1.57715379],
       [ 0.67472846, -1.57668299],
       [ 0.67610104, -1.57702288],
       [ 0.67609456, -1.5770001 ],
       [ 0.67445269, -1.57663835],
       [ 0.67419124, -1.57660545],
       [ 0.67284389, -1.5766204 ],
       [ 0.67206867, -1.57672767],
       [ 0.67353433, -1.57612079],
       [ 0.67427735, -1.57612963],
       [ 0.67467839, -1.57614058],
       [ 0.67098646, -1.57733557],
       [ 0.67207116, -1.57649497],
       [ 0.67045244, -1.57769841],
       [ 0.67356495, -1.57594582],
       [ 0.67431941, -1.57585673],
       [ 0.6735679 , -1.57554647],
       [ 0.67295611, -1.57536949],
       [ 0.67384175, -1.57500238],
       [ 0.67693716, -1.5769597 ],
       [ 0.67679249, -1.57665285],
       [ 0.67735185, -1.57602636],
       [ 0.67661216, -1.575683  ],
       [ 0.67447347, -1.57535591],
       [ 0.67434194, -1.57536345],
       [ 0.67432407, -1.57489499],
       [ 0.6742729 , -1.57488546],
       [ 0.67421731, -1.57457938],
       [ 0.67423213, -1.57414478],
       [ 0.67412823, -1.57417474],
       [ 0.67413643, -1.57412256],
       [ 0.67415092, -1.57408262]])

In [6]:
dist.pairwise(locations[['latitude','longitude']].to_numpy())*3798

array([[0.00000000e+00, 2.11647210e+02, 2.11172651e+02, ...,
        2.18137515e+02, 2.18285417e+02, 2.18393645e+02],
       [2.11647210e+02, 0.00000000e+00, 2.64127480e+00, ...,
        1.73517421e+01, 1.74630926e+01, 1.75746665e+01],
       [2.11172651e+02, 2.64127480e+00, 0.00000000e+00, ...,
        1.51356223e+01, 1.52564718e+01, 1.53736388e+01],
       ...,
       [2.18137515e+02, 1.73517421e+01, 1.51356223e+01, ...,
        0.00000000e+00, 1.57946672e-01, 2.86593260e-01],
       [2.18285417e+02, 1.74630926e+01, 1.52564718e+01, ...,
        1.57946672e-01, 0.00000000e+00, 1.30638570e-01],
       [2.18393645e+02, 1.75746665e+01, 1.53736388e+01, ...,
        2.86593260e-01, 1.30638570e-01, 0.00000000e+00]])

In [7]:
matrix = pd.DataFrame(dist.pairwise(locations[['latitude','longitude']].to_numpy())*3798,  columns=locations.Store.unique(), index=locations.Store.unique())
matrix

,Dunkin'0,McDonald's1,McDonald's2,McDonald's3,McDonald's4,McDonald's5,McDonald's6,McDonald's7,McDonald's8,McDonald's9,...,Starbucks308,Starbucks309,Starbucks310,Starbucks311,Starbucks312,Starbucks313,Starbucks314,Starbucks315,Starbucks316,Starbucks317
Dunkin'0,0.000000,211.647210,211.172651,211.142883,210.747480,6.162410,6.388456,7.981512,4.701138,6.879233,...,212.397940,214.470552,214.526614,215.909771,215.968323,216.898402,218.162749,218.137515,218.285417,218.393645
McDonald's1,211.647210,0.000000,2.641275,2.078545,1.111231,205.671785,205.590654,204.396742,207.407226,205.640360,...,24.471415,16.925365,16.451116,16.944722,16.782403,17.017832,17.731027,17.351742,17.463093,17.574667
McDonald's2,211.172651,2.641275,0.000000,0.581795,1.987356,205.216496,205.141946,203.964565,206.958239,205.208155,...,21.867814,14.437374,13.973203,14.551422,14.397491,14.701361,15.501248,15.135622,15.256472,15.373639
McDonald's3,211.142883,2.078545,0.581795,0.000000,1.417046,205.182336,205.106314,203.925228,206.922695,205.168841,...,22.448954,15.013317,14.548051,15.116277,14.961181,15.255477,16.042409,15.674414,15.793795,15.910119
McDonald's4,210.747480,1.111231,1.987356,1.417046,0.000000,204.776830,204.697368,203.507656,206.513897,204.751286,...,23.812905,16.424274,15.960477,16.533322,16.378173,16.669557,17.447943,17.078071,17.196191,17.311767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Starbucks313,216.898402,17.017832,14.701361,15.255477,16.669557,211.055729,211.015010,209.924864,212.825360,211.165185,...,9.666037,2.500727,2.373884,1.020387,0.932328,0.000000,1.290683,1.247355,1.389799,1.495318
Starbucks314,218.162749,17.731027,15.501248,16.042409,17.447943,212.322397,212.282287,211.193715,214.092461,212.433934,...,10.124194,3.708105,3.639565,2.252985,2.202979,1.290683,0.000000,0.404503,0.369385,0.359358
Starbucks315,218.137515,17.351742,15.135622,15.674414,17.078071,212.293484,212.252379,211.161176,214.062839,212.401568,...,10.439761,3.741554,3.619027,2.262690,2.179118,1.247355,0.404503,0.000000,0.157947,0.286593
Starbucks316,218.285417,17.463093,15.256472,15.793795,17.196191,212.441884,212.400911,211.310055,214.211334,212.550425,...,10.478966,3.876526,3.763476,2.400012,2.322118,1.389799,0.369385,0.157947,0.000000,0.130639
Starbucks317,218.393645,17.574667,15.373639,15.910119,17.311767,212.550772,212.509978,211.419588,214.320350,212.659927,...,10.482648,3.971209,3.868741,2.498338,2.426639,1.495318,0.359358,0.286593,0.130639,0.000000

In [8]:
matrix = matrix.replace(0, 5)
nearby = matrix[(matrix <= 1).any()]
nearby

,Dunkin'0,McDonald's1,McDonald's2,McDonald's3,McDonald's4,McDonald's5,McDonald's6,McDonald's7,McDonald's8,McDonald's9,...,Starbucks308,Starbucks309,Starbucks310,Starbucks311,Starbucks312,Starbucks313,Starbucks314,Starbucks315,Starbucks316,Starbucks317
Dunkin'0,5.000000,211.647210,211.172651,211.142883,210.747480,6.162410,6.388456,7.981512,4.701138,6.879233,...,212.397940,214.470552,214.526614,215.909771,215.968323,216.898402,218.162749,218.137515,218.285417,218.393645
McDonald's2,211.172651,2.641275,5.000000,0.581795,1.987356,205.216496,205.141946,203.964565,206.958239,205.208155,...,21.867814,14.437374,13.973203,14.551422,14.397491,14.701361,15.501248,15.135622,15.256472,15.373639
McDonald's3,211.142883,2.078545,0.581795,5.000000,1.417046,205.182336,205.106314,203.925228,206.922695,205.168841,...,22.448954,15.013317,14.548051,15.116277,14.961181,15.255477,16.042409,15.674414,15.793795,15.910119
McDonald's4,210.747480,1.111231,1.987356,1.417046,5.000000,204.776830,204.697368,203.507656,206.513897,204.751286,...,23.812905,16.424274,15.960477,16.533322,16.378173,16.669557,17.447943,17.078071,17.196191,17.311767
McDonald's5,6.162410,205.671785,205.216496,205.182336,204.776830,5.000000,0.524981,2.213247,1.808932,1.820519,...,206.639456,208.633529,208.684961,210.069463,210.126284,211.055729,212.322397,212.293484,212.441884,212.550772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Starbucks313,216.898402,17.017832,14.701361,15.255477,16.669557,211.055729,211.015010,209.924864,212.825360,211.165185,...,9.666037,2.500727,2.373884,1.020387,0.932328,5.000000,1.290683,1.247355,1.389799,1.495318
Starbucks314,218.162749,17.731027,15.501248,16.042409,17.447943,212.322397,212.282287,211.193715,214.092461,212.433934,...,10.124194,3.708105,3.639565,2.252985,2.202979,1.290683,5.000000,0.404503,0.369385,0.359358
Starbucks315,218.137515,17.351742,15.135622,15.674414,17.078071,212.293484,212.252379,211.161176,214.062839,212.401568,...,10.439761,3.741554,3.619027,2.262690,2.179118,1.247355,0.404503,5.000000,0.157947,0.286593
Starbucks316,218.285417,17.463093,15.256472,15.793795,17.196191,212.441884,212.400911,211.310055,214.211334,212.550425,...,10.478966,3.876526,3.763476,2.400012,2.322118,1.389799,0.369385,0.157947,5.000000,0.130639
Starbucks317,218.393645,17.574667,15.373639,15.910119,17.311767,212.550772,212.509978,211.419588,214.320350,212.659927,...,10.482648,3.971209,3.868741,2.498338,2.426639,1.495318,0.359358,0.286593,0.130639,5.000000

In [9]:
proximity_list = []
headers = ['store1', 'store2', 'distance']
for index, row in nearby.iterrows():
    for i in range(len(nearby.columns)): 
        if row[i] <=1:
            stores = [row.index[i], index]
            stores_ordered = sorted(stores)
            stores_ordered.append(row[i])
            proximity_list.append(stores_ordered)
proximity = pd.DataFrame(pd.DataFrame(proximity_list, columns=headers)).drop_duplicates()
proximity

           store1        store2  distance
0        Dunkin'0  McDonald's45  0.200160
1     McDonald's2   McDonald's3  0.581795
2     McDonald's2  Starbucks297  0.054356
4     McDonald's3  Starbucks297  0.527563
5     McDonald's4  Starbucks299  0.373667
..            ...           ...       ...
348  Starbucks314  Starbucks316  0.369385
349  Starbucks314  Starbucks317  0.359358
354  Starbucks315  Starbucks316  0.157947
355  Starbucks315  Starbucks317  0.286593
361  Starbucks316  Starbucks317  0.130639

[184 rows x 3 columns]

In [32]:
proximity2 = proximity.merge(locations1, left_on="store1", right_on="Store", how="left")
proximity3 = proximity2.merge(locations1, left_on="store2", right_on="Store", how="left")
proximity4 = proximity3[['store1', 'store2', 'distance', 'latitude_x', 'latitude_y']]
proximity4
locations3 = pd.DataFrame(locations2[['Store', 'latitude']])
proximity5 = proximity4.merge(locations3, left_on="latitude_x", right_on='latitude', how="left").drop('latitude_x', axis=1)
proximity6 = proximity5.merge(locations3, left_on="latitude_y", right_on='latitude', how="left").drop(['latitude_y','latitude_x'], axis=1)
prox_filter = proximity6.loc[proximity6['Store_x'] == "Panera Bread"]
prox_filter2 = prox_filter.loc[prox_filter['Store_y'] == "Starbucks"]
prox_filter3 = prox_filter2.merge(locations1, left_on="store1", right_on="Store", how="left").drop("Store", axis=1)
prox_filter3

,store1,store2,distance,Store_x,Store_y,latitude,longitude
0,Panera Bread224,Starbucks243,0.011673,Panera Bread,Starbucks,38.742399,-90.634926
1,Panera Bread225,Starbucks314,0.291251,Panera Bread,Starbucks,38.626338,-90.190806
2,Panera Bread225,Starbucks315,0.179536,Panera Bread,Starbucks,38.626338,-90.190806
3,Panera Bread225,Starbucks316,0.078174,Panera Bread,Starbucks,38.626338,-90.190806
4,Panera Bread225,Starbucks317,0.132132,Panera Bread,Starbucks,38.626338,-90.190806
5,Panera Bread227,Starbucks309,0.350607,Panera Bread,Starbucks,38.639194,-90.261171
6,Panera Bread227,Starbucks310,0.151229,Panera Bread,Starbucks,38.639194,-90.261171
7,Panera Bread228,Starbucks309,0.040158,Panera Bread,Starbucks,38.645055,-90.260990
8,Panera Bread228,Starbucks310,0.538630,Panera Bread,Starbucks,38.645055,-90.260990
9,Panera Bread229,Starbucks294,0.038981,Panera Bread,Starbucks,38.591253,-90.305201
10,Panera Bread229,Starbucks300,0.531985,Panera Bread,Starbucks,38.591253,-90.305201
11,Panera Bread230,Starbucks303,0.078038,Panera Bread,Starbucks,38.556442,-90.262550
12,Panera Bread231,Starbucks304,0.417476,Panera Bread,Starbucks,38.602036,-90.241960
13,Panera Bread232,Starbucks255,0.374371,Panera Bread,Starbucks,38.793643,-90.622987

In [33]:
prox_filter3.to_csv('sbux_panera_conj.csv', index=False)